# Readme
* Recommendation Engine : Contents Based Filtering
* Used data for compute cosine similarity : steam store games - steam.csv
* Used data for recommendation : steam user games
* rating = (((positive_rating - negative_rating)/2(positive_rating + negative_rating)) + 0.5) * 10

### recommend_game(df, appid, top=10)
* df is the data about contents of games
* The top 10 games are recommended in order of highest rating
* Result is the dataframe of games

### recommend_game_nameLIst(df, appid, top=10)
* df is the data about contents of games
* The top 10 games are recommended in order of highest rating
* Result is the list of the name of games

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
warnings.filterwarnings(action='ignore')

In [2]:
df = pd.read_csv('steam.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   appid             27075 non-null  int64  
 1   name              27075 non-null  object 
 2   release_date      27075 non-null  object 
 3   english           27075 non-null  int64  
 4   developer         27075 non-null  object 
 5   publisher         27075 non-null  object 
 6   platforms         27075 non-null  object 
 7   required_age      27075 non-null  int64  
 8   categories        27075 non-null  object 
 9   genres            27075 non-null  object 
 10  steamspy_tags     27075 non-null  object 
 11  achievements      27075 non-null  int64  
 12  positive_ratings  27075 non-null  int64  
 13  negative_ratings  27075 non-null  int64  
 14  average_playtime  27075 non-null  int64  
 15  median_playtime   27075 non-null  int64  
 16  owners            27075 non-null  object

In [4]:
df.head()

appid                       name release_date  english         developer  \
0     10             Counter-Strike   2000-11-01        1             Valve   
1     20      Team Fortress Classic   1999-04-01        1             Valve   
2     30              Day of Defeat   2003-05-01        1             Valve   
3     40         Deathmatch Classic   2001-06-01        1             Valve   
4     50  Half-Life: Opposing Force   1999-11-01        1  Gearbox Software   

  publisher          platforms  required_age  \
0     Valve  windows;mac;linux             0   
1     Valve  windows;mac;linux             0   
2     Valve  windows;mac;linux             0   
3     Valve  windows;mac;linux             0   
4     Valve  windows;mac;linux             0   

                                          categories  genres  \
0  Multi-player;Online Multi-Player;Local Multi-P...  Action   
1  Multi-player;Online Multi-Player;Local Multi-P...  Action   
2              Multi-player;Valve Anti-Cheat enabled  Action   
3  Multi-player;Online Multi-Player;Local Multi-P...  Action   
4  Single-player;Multi-player;Valve Anti-Cheat en...  Action   

                  steamspy_tags  achievements  positive_ratings  \
0        Action;FPS;Multiplayer             0            124534   
1        Action;FPS;Multiplayer             0              3318   
2  FPS;World War II;Multiplayer             0              3416   
3        Action;FPS;Multiplayer             0              1273   
4             FPS;Action;Sci-fi             0              5250   

   negative_ratings  average_playtime  median_playtime             owners  \
0              3339             17612              317  10000000-20000000   
1               633               277               62   5000000-10000000   
2               398               187               34   5000000-10000000   
3               267               258              184   5000000-10000000   
4               288               624              415   5000000-10000000   

   price  
0   7.19  
1   3.99  
2   3.99  
3   3.99  
4   3.99

In [5]:
df['rating'] = ((df['positive_ratings'] - df['negative_ratings'])/(2 * (df['positive_ratings'] + df['negative_ratings'])) + 0.5) * 10.0
df

appid                        name release_date  english  \
0           10              Counter-Strike   2000-11-01        1   
1           20       Team Fortress Classic   1999-04-01        1   
2           30               Day of Defeat   2003-05-01        1   
3           40          Deathmatch Classic   2001-06-01        1   
4           50   Half-Life: Opposing Force   1999-11-01        1   
...        ...                         ...          ...      ...   
27070  1065230             Room of Pandora   2019-04-24        1   
27071  1065570                   Cyber Gun   2019-04-23        1   
27072  1065650            Super Star Blast   2019-04-24        1   
27073  1066700  New Yankee 7: Deer Hunters   2019-04-17        1   
27074  1069460                   Rune Lord   2019-04-24        1   

                developer             publisher          platforms  \
0                   Valve                 Valve  windows;mac;linux   
1                   Valve                 Valve  windows;mac;linux   
2                   Valve                 Valve  windows;mac;linux   
3                   Valve                 Valve  windows;mac;linux   
4        Gearbox Software                 Valve  windows;mac;linux   
...                   ...                   ...                ...   
27070         SHEN JIAWEI           SHEN JIAWEI            windows   
27071      Semyon Maximov      BekkerDev Studio            windows   
27072         EntwicklerX           EntwicklerX            windows   
27073  Yustas Game Studio  Alawar Entertainment        windows;mac   
27074    Adept Studios GD  Alawar Entertainment        windows;mac   

       required_age                                         categories  \
0                 0  Multi-player;Online Multi-Player;Local Multi-P...   
1                 0  Multi-player;Online Multi-Player;Local Multi-P...   
2                 0              Multi-player;Valve Anti-Cheat enabled   
3                 0  Multi-player;Online Multi-Player;Local Multi-P...   
4                 0  Single-player;Multi-player;Valve Anti-Cheat en...   
...             ...                                                ...   
27070             0                   Single-player;Steam Achievements   
27071             0                                      Single-player   
27072             0  Single-player;Multi-player;Co-op;Shared/Split ...   
27073             0                          Single-player;Steam Cloud   
27074             0                          Single-player;Steam Cloud   

                       genres                 steamspy_tags  achievements  \
0                      Action        Action;FPS;Multiplayer             0   
1                      Action        Action;FPS;Multiplayer             0   
2                      Action  FPS;World War II;Multiplayer             0   
3                      Action        Action;FPS;Multiplayer             0   
4                      Action             FPS;Action;Sci-fi             0   
...                       ...                           ...           ...   
27070  Adventure;Casual;Indie        Adventure;Indie;Casual             7   
27071  Action;Adventure;Indie        Action;Indie;Adventure             0   
27072     Action;Casual;Indie           Action;Indie;Casual            24   
27073  Adventure;Casual;Indie        Indie;Casual;Adventure             0   
27074  Adventure;Casual;Indie        Indie;Casual;Adventure             0   

       positive_ratings  negative_ratings  average_playtime  median_playtime  \
0                124534              3339             17612              317   
1                  3318               633               277               62   
2                  3416               398               187               34   
3                  1273               267               258              184   
4                  5250               288               624              415   
...                 ...               ...               .

In [6]:
contents = df[['categories', 'genres', 'steamspy_tags']]
contents

categories  \
0      Multi-player;Online Multi-Player;Local Multi-P...   
1      Multi-player;Online Multi-Player;Local Multi-P...   
2                  Multi-player;Valve Anti-Cheat enabled   
3      Multi-player;Online Multi-Player;Local Multi-P...   
4      Single-player;Multi-player;Valve Anti-Cheat en...   
...                                                  ...   
27070                   Single-player;Steam Achievements   
27071                                      Single-player   
27072  Single-player;Multi-player;Co-op;Shared/Split ...   
27073                          Single-player;Steam Cloud   
27074                          Single-player;Steam Cloud   

                       genres                 steamspy_tags  
0                      Action        Action;FPS;Multiplayer  
1                      Action        Action;FPS;Multiplayer  
2                      Action  FPS;World War II;Multiplayer  
3                      Action        Action;FPS;Multiplayer  
4                      Action             FPS;Action;Sci-fi  
...                       ...                           ...  
27070  Adventure;Casual;Indie        Adventure;Indie;Casual  
27071  Action;Adventure;Indie        Action;Indie;Adventure  
27072     Action;Casual;Indie           Action;Indie;Casual  
27073  Adventure;Casual;Indie        Indie;Casual;Adventure  
27074  Adventure;Casual;Indie        Indie;Casual;Adventure  

[27075 rows x 3 columns]

In [7]:
cols = contents.columns.to_list()
cols

['categories', 'genres', 'steamspy_tags']

In [8]:
game_data = pd.DataFrame(columns=['name', 'contents'])
game_data

Empty DataFrame
Columns: [name, contents]
Index: []

In [9]:
for i in range(df.shape[0]):
    data = df.loc[i]
    name = data['name']
    contents = ''
    merged = []
    for col in cols:
        origin = data[col]
        parsed = origin.split(';')
        if (col == 'categories') and (len(parsed) > 5):
            parsed = parsed[:5]
        for k in range(len(parsed)):
            parse = parsed[k]
            parse = parse.replace(' ', '_')
            parsed[k] = parse
        merged = merged + parsed
        
    set_merged = set(merged)
    merged = list(set_merged)
    for j in range(len(merged)):
        if j == 0:
            contents = contents + merged[j]
        else :
            contents = contents + ' ' + merged[j]
    game_data.loc[i, 'name'] = name
    game_data.loc[i, 'contents'] = contents
    if i % 10000 == 0:
        print(i, 'finished')

0 finished
10000 finished
20000 finished


In [10]:
game_data

name  \
0                  Counter-Strike   
1           Team Fortress Classic   
2                   Day of Defeat   
3              Deathmatch Classic   
4       Half-Life: Opposing Force   
...                           ...   
27070             Room of Pandora   
27071                   Cyber Gun   
27072            Super Star Blast   
27073  New Yankee 7: Deer Hunters   
27074                   Rune Lord   

                                                contents  
0      Multiplayer Local_Multi-Player Valve_Anti-Chea...  
1      Multiplayer Local_Multi-Player Valve_Anti-Chea...  
2      World_War_II Multiplayer Valve_Anti-Cheat_enab...  
3      Multiplayer Local_Multi-Player Valve_Anti-Chea...  
4      Sci-fi Single-player Valve_Anti-Cheat_enabled ...  
...                                                  ...  
27070  Adventure Indie Single-player Casual Steam_Ach...  
27071               Adventure Indie Single-player Action  
27072  Single-player Indie Casual Action Steam_Achiev...  
27073   Steam_Cloud Single-player Indie Adventure Casual  
27074   Steam_Cloud Single-player Indie Adventure Casual  

[27075 rows x 2 columns]

In [11]:
cnt_vec = CountVectorizer()

vec = cnt_vec.fit_transform(game_data['contents'])

sim = cosine_similarity(vec, vec).argsort()[:, ::-1]
print(sim)

[[    0     1     3 ... 26302 10158 13504]
 [    0     1     3 ... 26302 10158 13504]
 [    2    15    13 ... 19211  5875 19446]
 ...
 [ 6380 27072  5676 ...  7992  9977  1263]
 [27074 26795 27044 ... 19388 23891 25031]
 [27074 26795 27044 ... 19388 23891 25031]]


In [25]:
def recommend_game(df, appid, top=10):
    # get the data of game that user played
    target_game_idx = df[df['appid'] == appid].index.values
        
    # get the similarity based on the cosine similarity
    sim_idx = sim[target_game_idx, :top].reshape(-1)
    
    # remove index of itself
    sim_idx = sim_idx[sim_idx != target_game_idx]

    # make the name list of top 10 recommended games
    result = df.iloc[sim_idx].sort_values('rating', 
                                               ascending=False)[:10]    
    
    return result

In [26]:
# print a result of Codename CURE (appid = 355180)
print('User Played "Codename CURE"')
print('Recommended games are...')
recommend_game(df, 355180)

User Played "Codename CURE"
Recommended games are...


appid                                    name release_date  english  \
28       1250                           Killing Floor   2009-05-14        1   
3391   306020                             Bloons TD 5   2014-11-19        1   
16093  678800                   SAS: Zombie Assault 4   2017-10-16        1   
1727   236390                             War Thunder   2013-08-15        1   
24027  915580                Dungeon Hunter Champions   2018-12-19        1   
17204  709870                             West of Red   2018-03-07        1   
17718  724430                            Knights Hunt   2018-03-20        1   
24173  921590  DISSIDIA FINAL FANTASY NT Free Edition   2019-03-12        1   
17067  705710                      Sense of The Devil   2017-09-22        1   

                                    developer             publisher  \
28                       Tripwire Interactive  Tripwire Interactive   
3391                               Ninja Kiwi            Ninja Kiwi   
16093                              Ninja Kiwi            Ninja Kiwi   
1727                     Gaijin Entertainment  Gaijin Entertainment   
24027                                Gameloft              Gameloft   
17204                             Racing Bros               ANPA.US   
17718                             Racing Bros               ANPA.US   
24173  Square Enix;KOEI TECMO GAMES CO., LTD.           Square Enix   
17067                             Racing Bros               ANPA.US   

               platforms  required_age  \
28     windows;mac;linux             0   
3391         windows;mac             0   
16093        windows;mac             0   
1727   windows;mac;linux             0   
24027            windows             0   
17204  windows;mac;linux             0   
17718  windows;mac;linux             0   
24173            windows             0   
17067  windows;mac;linux             0   

                                              categories  \
28     Single-player;Multi-player;Co-op;Cross-Platfor...   
3391   Single-player;Co-op;Online Co-op;Cross-Platfor...   
16093  Single-player;Online Multi-Player;Online Co-op...   
1727   Single-player;MMO;Co-op;Cross-Platform Multipl...   
24027  Single-player;Online Multi-Player;Online Co-op...   
17204  Single-player;Co-op;Online Co-op;Cross-Platfor...   
17718  Single-player;Co-op;Online Co-op;Cross-Platfor...   
24173  Multi-player;Online Multi-Player;Co-op;Online ...   
17067  Single-player;Co-op;Online Co-op;Cross-Platfor...   

                                                  genres  \
28                                                Action   
3391                                     Action;Strategy   
16093                            Action;Free to Play;RPG   
1727   Action;Free to Play;Massively Multiplayer;Simu...   
24027                            Action;Free to Play;RPG   
17204               Violent;Gore;Action;Indie;Simulation   
17718               Violent;Gore;Action;Indie;Simulation   
24173                                Action;Free to Play   
17067                          Violent;Gore;Action;Indie   

                               steamspy_tags  achievements  positive_ratings  \
28                         FPS;Zombies;Co-op           285             53710   
3391            Tower Defense;Strategy;Co-op           125              3808   
16093       Free to Play;Multiplayer;Zombies            59              2086   
1727   Free to Play;World War II;Multiplayer            46             83852   
24027                Free to Play;RPG;Action           106               124   
17204                      Action;Indie;Gore             5                22   
17718                      Action;Indie;Gore          2001                24   
24173        Free to Play;Action;Multiplayer            56               620   
17067                      Action;Gore;Indie          1011                29   

       negative_ratings  average_playtime  median_playtime             owners  \
2

In [12]:
def recommend_game_nameLIst(df, appid, top=10):
    # get the data of game that user played
    target_game_idx = df[df['appid'] == appid].index.values
        
    # get the similarity based on the cosine similarity
    sim_idx = sim[target_game_idx, :top].reshape(-1)
    
    # remove index of itself
    sim_idx = sim_idx[sim_idx != target_game_idx]

    # make the name list of top 10 recommended games
    recommended = df.iloc[sim_idx].sort_values('rating', 
                                               ascending=False)[:10]    
    result = recommended['name'].to_list()
    
    return result

In [24]:
# print a result of Codename CURE (appid = 355180)
print('User Played "Codename CURE"')
print('Recommended games are...')
recommend_game_nameLIst(df, 355180)

User Played "Codename CURE"
Recommended games are...


['Killing Floor',
 'Bloons TD 5',
 'SAS: Zombie Assault 4',
 'War Thunder',
 'Dungeon Hunter Champions',
 'West of Red',
 'Knights Hunt',
 'DISSIDIA FINAL FANTASY NT Free Edition',
 'Sense of The Devil']

In [14]:
origin_data = pd.read_csv('data_join.csv')

In [15]:
origin_data.shape

(92883, 23)

In [16]:
recommendList = []
for i in range(origin_data.shape[0]):
    gameName = recommend_game_nameLIst(df, origin_data.loc[i, 'appid'])
    recommendList.append(';'.join(gameName))
    if i % 10000 == 0:
        print(i, ': finished')

0 : finished
10000 : finished
20000 : finished
30000 : finished
40000 : finished
50000 : finished
60000 : finished
70000 : finished
80000 : finished
90000 : finished


In [17]:
recommendResult = pd.Series(data=recommendList)

In [18]:
origin_data['recommended'] = recommendResult

In [19]:
origin_data.head()

Unnamed: 0      user_id       name  purchase   1.0    0     appid  \
0        1394  151603712.0  Fallout 4  purchase   1.0  0.0  377160.0   
1        1395  151603712.0  Fallout 4      play  87.0  0.0  377160.0   
2        1396   87445402.0  Fallout 4  purchase   1.0  0.0  377160.0   
3        1397   87445402.0  Fallout 4      play  83.0  0.0  377160.0   
4        1398   25096601.0  Fallout 4  purchase   1.0  0.0  377160.0   

  release_date  english              developer  ... genres  \
0   2015-11-09      1.0  Bethesda Game Studios  ...    RPG   
1   2015-11-09      1.0  Bethesda Game Studios  ...    RPG   
2   2015-11-09      1.0  Bethesda Game Studios  ...    RPG   
3   2015-11-09      1.0  Bethesda Game Studios  ...    RPG   
4   2015-11-09      1.0  Bethesda Game Studios  ...    RPG   

                             steamspy_tags  achievements positive_ratings  \
0  Open World;Post-apocalyptic;Exploration          84.0         110376.0   
1  Open World;Post-apocalyptic;Exploration          84.0         110376.0   
2  Open World;Post-apocalyptic;Exploration          84.0         110376.0   
3  Open World;Post-apocalyptic;Exploration          84.0         110376.0   
4  Open World;Post-apocalyptic;Exploration          84.0         110376.0   

  negative_ratings average_playtime  median_playtime            owners  price  \
0          45377.0           4822.0           2904.0  5000000-10000000  19.99   
1          45377.0           4822.0           2904.0  5000000-10000000  19.99   
2          45377.0           4822.0           2904.0  5000000-10000000  19.99   
3          45377.0           4822.0           2904.0  5000000-10000000  19.99   
4          45377.0           4822.0           2904.0  5000000-10000000  19.99   

                                         recommended  
0  The Witcher® 3: Wild Hunt;Fallout 2: A Post Nu...  
1  The Witcher® 3: Wild Hunt;Fallout 2: A Post Nu...  
2  The Witcher® 3: Wild Hunt;Fallout 2: A Post Nu...  
3  The Witcher® 3: Wild Hunt;Fallout 2: A Post Nu...  
4  The Witcher® 3: Wild Hunt;Fallout 2: A Post Nu...  

[5 rows x 24 columns]

In [20]:
origin_data.to_csv("content_recommendation_result.csv", index = False)